name: booking-order-app
services:
  user-service:
    container_name: user-service
    # image: maulanairfanf/user-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
    driver: bridge
